title: arpit04tripathi Blog
author: arpit04tripathi
description: >- # this means to ignore newlines until "baseurl:"
  Blogs page 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# social
# twitter_username:
# github_username:

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  private:
    output: true
