remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


title: arpit04tripathi Blog
description: little blog site for personal use

# configs
show_downloads: false
show_github: false
